server:
  port: 8002


eureka:
  client:
    service-url:
      defaultZone: http://localhost:18761/eureka
spring:
  profiles:
    active: prod
  application:
    name: device-data
#设置feign 客户端超时时间（openFeign默认支持ribbon）
ribbon:
  #指的是建立连接所用的时间，适用于网络状况正常的情况下，两端连接所用的时间
  ReadTimeout: 500000
  #指的是建立连接后从服务器读取到可用资源所用的时间
  ConnectTimeout: 500000

task:
  pool:
    # 核心线程池大小
    corePoolSize: 10
    # 最大线程数
    maxPoolSize: 30
    # 活跃时间
    eepAliveSeconds: 60
    # 队列容量
    queueCapacity: 50