server:
  port: 8001
spring:
  profiles:
    active: prod
  application:
    name: auth-center



mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #开启sql日志
#    log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl
  mapper-locations:
    - classpath:mapper/**/*.xml
  global-config:
    db-config:
      table-underline: false
task:
  pool:
    # 核心线程池大小
    corePoolSize: 4
    # 最大线程数
    maxPoolSize: 8
    # 活跃时间
    eepAliveSeconds: 60
    # 队列容量
    queueCapacity: 50
#设置feign 客户端超时时间（openFeign默认支持ribbon）
ribbon:
  #指的是建立连接所用的时间，适用于网络状况正常的情况下，两端连接所用的时间
  ReadTimeout: 500000
  #指的是建立连接后从服务器读取到可用资源所用的时间
  ConnectTimeout: 500000

# 登录相关配置
login:
  #  是否限制单用户登录
  single-login: false
