
spring:
  datasource:
    druid:
      db-type: com.alibaba.druid.pool.DruidDataSource
      driverClassName: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://device.misaki.world:3306/device_test?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false
#      url: jdbc:mysql://192.168.0.1:3306/device_test?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false
      username: root
      password: device_mysql_001
#      url: jdbc:mysql://localhost:3306/device_test?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false
#      username: root
#      password: hsp
      initial-size: 40
      max-active: 100
      min-idle: 40
      max-wait: 2000
      time-between-eviction-runs-millis: 300000
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #开启sql日志
    log-impl: org.apache.ibatis.logging.nologging.NoLoggingImpl
  mapper-locations:
    - classpath:mapper/**/*.xml
  global-config:
    db-config:
      table-underline: false