eureka:
  client:
    service-url:
      defaultZone: http://localhost:18761/eureka/

#配置数据源
spring:
  datasource:
    druid:
      driverClassName: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://device.misaki.world:3306/device_test?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false
#      url: jdbc:mysql://192.168.0.1:3306/device_test?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false
      username: root
      password: device_mysql_001
#      url: jdbc:mysql://localhost:3306/device_test?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false
#      username: root
#      password: hsp
      initial-size: 40
      max-active: 100
      min-idle: 40
      max-wait: 2000
      time-between-eviction-runs-millis: 300000 
    
    
    type: com.alibaba.druid.pool.DruidDataSource
  

  redis:
    host: 192.168.0.2
    port: 6379
    # Redis 服务器连接密码(默认为0)
    password: device_redis_001
    # 连接超时时间（毫秒）
    timeout: 10000

#  redis:
#    host: 127.0.0.1
#    port: 6379
#    # Redis 服务器连接密码(默认为0)
#    password:
#    timeout: 10000
#    # 连接超时时间（毫秒）


