eureka:
  client:
    service-url:
      defaultZone: http://localhost:18761/eureka/

#配置数据源
spring:
  datasource:
    druid:
      driverClassName: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/device?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false
      username: root
      password: 4521323

      initial-size: 40
      max-active: 100
      min-idle: 40
      max-wait: 2000
      time-between-eviction-runs-millis: 300000


    type: com.alibaba.druid.pool.DruidDataSource


  redis:
    # 地址
    host: 127.0.0.1
    # 端口，默认为6379
    port: 6379
    # 密码
    password:
    # 连接超时时间
    timeout: 10s


